#Monitoring endpoints
spring:
  shop:
    showItems:
      url: http://localhost:8080/api/items
    addOrder:
      url: http://localhost:8080/api/addOrder

management:
   endpoints:
      web:
         exposure:
            include: info, health, configprops, logfile, metrics, env, loggers