#Monitoring endpoints
spring:
  shop:
    api:
      url: http://localhost:8080

management:
   endpoints:
      web:
         exposure:
            include: info, health, configprops, logfile, metrics, env, loggers