#Monitoring endpoints
spring:
  shop:
    api:
      url: http://localhost:8080
    showItems:
      url: ${spring.shop.api.url}/api/items
    addOrder:
      url: ${spring.shop.api.url}/api/addOrder

management:
   endpoints:
      web:
         exposure:
            include: info, health, configprops, logfile, metrics, env, loggers