spring:
  application:
    name: '@project.name@'
  profiles:
    active: '@spring.profiles.active@'
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    fr.training.samples.spring.shop: INFO
server:
  port: 8081