spring:
  datasource:
    url: jdbc:mysql://129.159.254.115:3306/formationdb
    username: monty
    password: some_pass
#Monitoring endpoints   
management:
   endpoints:
      web:
         exposure:
            include: info, health, configprops, logfile, metrics, env, loggers