spring:
  datasource:
    url: jdbc:mysql://localhost:3306/formationdb
    username: root
    password: my-secret-pw
#Monitoring endpoints   
management:
  endpoints:
    web:
      exposure:
        include: info, health, configprops, logfile, metrics, env, loggers
    
    #logging:
    #level:
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
springdoc:
  show-actuator: true